# Generated by Django 4.1.2 on 2022-10-15 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='fole',
            new_name='role',
        ),
    ]
