# Generated by Django 4.1.2 on 2022-10-15 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_lacotion_department_lacation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='lacation',
            new_name='location',
        ),
    ]
